name: locales

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Install gettext
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext
      - name: Run locales check
        run: |
          make locales
        shell: bash